// // RobotBuilder Version: 2.0
// //
// // This file was generated by RobotBuilder. It contains sections of
// // code that are automatically generated and assigned by robotbuilder.
// // These sections will be updated in the future when you export to
// // Java from RobotBuilder. Do not put any code or make any change in
// // the blocks indicating autogenerated code or it will be lost on an
// // update. Deleting the comments indicating the section will prevent
// // it from being updated in the future.


// package org.usfirst.frc6991.Crossbotics.subsystems;


// import org.usfirst.frc6991.Crossbotics.commands.*;
// import edu.wpi.first.wpilibj.livewindow.LiveWindow;
// import edu.wpi.first.wpilibj.command.Subsystem;
// import edu.wpi.first.wpilibj.PIDOutput;
// import edu.wpi.first.wpilibj.PIDSource;
// // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
// import edu.wpi.first.wpilibj.PWMVictorSPX;
// import edu.wpi.first.wpilibj.SpeedController;


// // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


// /**
//  *
//  */
// public class drive extends Subsystem {

//     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

//     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

//     public drive() {
//         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
//         left_Front_Mac =;
//         addChild("Left_Front_Mac",left_Front_Mac);
        
        
//         left_Rear_Mac;
//         addChild("Left_Rear_Mac",left_Rear_Mac);
//         left_Rear_Mac.setInverted(false);
        
//         right_Front_Mac;
//         addChild("Right_Front_Mac",right_Front_Mac);
//         right_Front_Mac.setInverted(true);
        
//         right_Rear_Mac;
//         addChild("Right_Rear_Mac",right_Rear_Mac);
//         right_Rear_Mac.setInverted(true);
        
//         addChild("Mecanums",mecanums);
//         mecanums.setSafetyEnabled(true);
//         mecanums.setExpiration(0.1);
//         mecanums.setMaxOutput(1.0);

        

//         // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
//     }

//     @Override
//     public void initDefaultCommand() {
//         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


//         // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

//         // Set the default command for a subsystem here.
//         // setDefaultCommand(new MySpecialCommand());
//     }

//     @Override
//     public void periodic() {
//         // Put code here to be run every loop

//     }

//     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

//     // Put methods for controlling this subsystem
//     // here. Call these from Commands.

// }

